### ISSUE TITLE
Animated cloud background eats massive amounts of CPU

### ISSUE THREAD

**Issue by dwfreed** [linode/blog#2]

**Comment by SirCmpwn** [comment]
There was an older version that used even more CPU, believe it or not. I'm not actually sure what the cause is - it's a pretty simple SVG with a pretty straightforward CSS3 animation applied. Any ideas?

**Comment by dwfreed** [comment]
TBH, it's cheesy as hell; I'd just get rid of it.

**Comment by SirCmpwn** [comment]
It's gotten rid of. Thanks for the feedback!
